
//login methods
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';


//signup methods
export const SIGNUP_SET_EMAIL = 'SIGNUP_SET_EMAIL';
export const SIGNUP_SET_PASSWORD = 'SIGNUP_SET_PASSWORD';
export const SIGNUP_SET_NAME = 'SIGNUP_SET_NAME';


//userDetails methods
export const REQUEST_TAGS = 'REQUEST_TAGS';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';


//VrScheduleGrid
export const FETCH_SCHEDULE_DATA = 'FETCH_SCHEDULE_DATA';
export const RECEIVE_SCHEDULE_DATA = 'RECEIVE_SCHEDULE_DATA';

//Profile Methode
export const TOGGLE_EDIT_PROFILE ='TOGGLE_EDIT_PROFILE';
export const RECEIVE_PROFILE_DATA = 'RECEIVE_PROFILE_DATA';
export const PROFILE_NAME_CHANGE ='PROFILE_NAME_CHANGE';
export const PROFILE_TITLE_CHANGE ='PROFILE_TITLE_CHANGE';
export const PROFILE_DESC_CHANGE = 'PROFILE_DESC_CHANGE';
export const PROFILE_INST_CHANGE = 'PROFILE_INST_CHANGE';
export const PROFILE_FIELD_CHANGE ='PROFILE_FIELD_CHANGE';

export const RECEIVE_NOTIS = 'RECEIVE_NOTIS';

